#global config
global:
  scrape_interval:     15s
  evaluation_interval: 5s
  # scrape_timeout:     1m
  scrape_timeout:     5s
  #query_log_file: <string>
  external_labels:
    monitor: 'app-monitor'
# Scrape configs only contain one scrape target
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    scrape_interval: 2s
    static_configs:
      - targets: ['app:8080']
